### ISSUE TITLE
Allow multiple plugins of the same type (e.g. `GithubActions` CI plugins)

### ISSUE THREAD

**Issue by nickrobinson251** [JuliaCI/PkgTemplates.jl#266]
Currently, if two plugins have the same type, the first plugin is used, see e.g. https://github.com/invenia/PkgTemplates.jl/pull/265#issuecomment-772536740 Why is that?

My use-case for multipl plugins of the same type is multiple `GitHubAction` CI plugins, e.g. for when if you want a different CI job for running on the Julia Nightly versions, or something like that. (Noticed at #265)

I think this is implemented at
https://github.com/invenia/PkgTemplates.jl/blob/238bfc11c037f341eff4889e0424a66d1edf7404/src/template.jl#L100
but i don't know why we do that.

I think it might be so that we can use a pattern like
```julia
for T in PluginTypes
   p = getplugin(tpl, T)
   ...
end
```
but i think that only appears one ([in the code for `view(p::Readme, ...`](https://github.com/invenia/PkgTemplates.jl/blob/238bfc11c037f341eff4889e0424a66d1edf7404/src/plugins/readme.jl#L30-L39)), and we could easily get the desired behaviour (sorting by the type `T` somehow) by writng the code slightly differently.

Is there any other reason to disallow multiple plugins of the same type?

**Comment by christopher-dG** [comment]
The reason is that we want default plugins to get removed if a user provides one of the same type, e.g. a `Readme` that produces a `.txt` file. We don't want to produce two READMEs, so we get rid of the first one. It would be fine to change that behaviour so it only removes default plugins and doesn't completely deduplicate the list.

**Comment by hannahilea** [comment]
Allowing multiple plugins of the same type is also a feature that I'd like---is there a reason that the initial implementation #269 was closed rather than left open for further tests/merging? I'd like to take this on, but don't want to continue down a path that was intentionally abandoned...

**Comment by nickrobinson251** [comment]
Please do pick this up! #269 was just closed as i didn't have time to finish it and i didn't want it to be left open in case it blocked others working on this issue

Thanks!
