### ISSUE TITLE
Add JuliaFormatter toml generator (maybe consistent with "code style")

### ISSUE THREAD

**Issue by jlperla** [JuliaCI/PkgTemplates.jl#328]
Now that the VS Code has moved to JuliaFormatter.jl, I would be great for a template plugin to generate files to support it (including your beloved `style = "blue"`!)  

It seems the architecture is to remove all formatting in the vscode extension itself, and do all formatting configuration in a 
`.JuliaFormatter.toml` file (cc @pfitzseb).  Which I fully agree with!  That means it is especially helpful to generate these files for new users.

The minimum configuration of a plugin to the PkgTemplates is to generate a file with `style = "blue"`, `="default"` or `="yas"`.   Personally that is enough for my purposes since I think that users can then modify it directly since it would be created in the correct place.  But to get fancy you could add in https://github.com/domluna/JuliaFormatter.jl/#formatting-options  as well.

BTW, my hope is to add this into the https://julia.quantecon.org/software_engineering/testing.html#project-setup  docs so that introductory users get in the habit of always using code formatting/code styles.

**Comment by nickrobinson251** [comment]
Sure, I think a `JuliaFormatter <: Plugin` would be a great addition!

**Comment by gdalle** [comment]
I accidentally duplicated this in #324

**Comment by gdalle** [comment]
> BTW, my hope is to add this into the https://julia.quantecon.org/software_engineering/testing.html#project-setup docs so that introductory users get in the habit of always using code formatting/code styles.

I'm currently on a rampage of PkgTemplates PR to teach people good coding practices. See #415 about my dreams for the `runtests.jl` file. If you have other similar ideas, I'll take 'em!

**Comment by nickrobinson251** [comment]
closed by https://github.com/JuliaCI/PkgTemplates.jl/pull/412
