### ISSUE TITLE
Fixing link for Travis CI badge

### ISSUE THREAD

**Issue by YanniPapandreou** [JuliaCI/PkgTemplates.jl#338]
Hi,

I was following a tutorial online for using PkgTemplates to create a Julia package. I used the following template:

```julia
using PkgTemplates

t = Template(; 
    user="YanniPapandreou",
    authors=["Yanni Papandreou"],
    plugins=[
        License(; name="MIT"),
        TravisCI(),
        Codecov(),
        Coveralls(),
        AppVeyor(),
    ],
)

t("MyExample")
```

The generated `README.md` file generated a Travis CI badge whose link did not work. This linked to `https://travis-ci.com/YanniPapandreou/MyExample.jl` instead of the correct link `https://app.travis-ci.com/YanniPapandreou/MyExample.jl`. I have changed the `CI.jl` code to use the correct link, the relevant changes are detailed below:

- Original:
```julia
badges(::TravisCI) = Badge(
    "Build Status",
    "https://travis-ci.com/{{{USER}}}/{{{PKG}}}.jl.svg?branch={{{BRANCH}}}",
    "https://travis-ci.com/{{{USER}}}/{{{PKG}}}.jl",
)
```
- Changed:
```julia
badges(::TravisCI) = Badge(
    "Build Status",
    "https://app.travis-ci.com/{{{USER}}}/{{{PKG}}}.jl.svg?branch={{{BRANCH}}}",
    "https://app.travis-ci.com/{{{USER}}}/{{{PKG}}}.jl",
)
```

I submitted but then closed a pull request as I read that it is better to first submit an issue; I am new to contributing to open source. If this is something that should be changed I am happy to reopen the pull request. Thanks :)

**Comment by nickrobinson251** [comment]
Welcome, and thanks for the issue and PR!

I re-opened the [PR](#337 ) and left a comment :) 

BTW, if don't have a particular reason to use Travis CI for your package I would recommend GithubActions for CI instead 😊
