### ISSUE TITLE
Hope Name generated dir MyPkg.jl rather than MyPkg

### ISSUE THREAD

**Issue by zsz00** [JuliaCI/PkgTemplates.jl#353]
using PkgTemplates
Template(interactive=true)("MyPkg.jl")

then generate the dir is MyPkg, why not MyPkg.jl ??

**Comment by nickrobinson251** [comment]
I don't know. And it always surprises me too. It's inconsistent with the directory name you get via `using Pkg; Pkg.generate("MyPkg.jl")`, or via cloning a repo (which tend to have the `.jl` suffix by convention). 

We should check there's not a good reason (cc @christopher-dG), and if not we could change it.
https://github.com/invenia/PkgTemplates.jl/blob/47aa85f0247dc5d2a695f97efcc245c37e414325/src/template.jl#L123

**Comment by christopher-dG** [comment]
I don't think there's any particularly good reason, might have just been a personal preference at the time (I always clone Julia repos without the .jl suffix). Feel free to change or make an option or whatever!

**Comment by 3f6a** [comment]
+1 to .jl suffix
