### ISSUE TITLE
Update URL in the package description

### ISSUE THREAD

**Issue by gdalle** [JuliaCI/PkgTemplates.jl#373]
On the top right corner of the repo, the URL still points to the (now dead) Invenia docs

**Comment by kalvotom** [comment]
I second that!

**Comment by nickrobinson251** [comment]
Done! (I think. Let me know if you meant somewhere else)

 ![image](https://user-images.githubusercontent.com/13448787/204276650-5bf19de1-7ba4-4495-8112-3df45ed9e984.png)
