### ISSUE TITLE
Default to Project.toml v1.0.0

### ISSUE THREAD

**Issue by oxinabox** [JuliaCI/PkgTemplates.jl#387]
Currently the default version number if you don't specify is 0.1.0 
I believe it should be 1.0.0-DEV.
Since the version number should be 1.0.0 when it is first released (i.e. registered).
So there is no point having it on anything else since before then it doesn't matter

I thought we made this change back when Invenia stopped doing 0.x versions.
But it seems not.

Is this a breaking change?

I talked about this in some detail on twitter recently
https://twitter.com/oxinabox_frames/status/1620538988842065920

**Comment by nickrobinson251** [comment]
yeah, let's do it

**Comment by nickrobinson251** [comment]
no it's not breaking (else we'd never be able to make improvements to anything)
