### ISSUE TITLE
Problem with CompatHelper 

### ISSUE THREAD

**Issue by martinmestre** [JuliaCI/PkgTemplates.jl#395]
Hello, thank you very much for the PkgTemplates package. I have started to use it. After pushing some code to GitHub, I have received the information that CompatHelper failed. Could you help me with this [problem](https://discourse.julialang.org/t/new-error-with-compathelper/97757). Thank you very much!

**Comment by oxinabox** [comment]
You are better off continuing with the discussion on discourse.
