### ISSUE TITLE
TagBot template is out of date

### ISSUE THREAD

**Issue by SamuraiAku** [JuliaCI/PkgTemplates.jl#403]
The TagBot template was updated about 6 months ago, adding many more explicit permissions.

See the [example file](https://github.com/JuliaRegistries/TagBot/blob/master/example.yml) and the [README](https://github.com/JuliaRegistries/TagBot/blob/master/README.md).

I could not get TagBot to work with my newly released package [PkgToSoftwareBOM.jl](https://github.com/SamuraiAku/PkgToSoftwareBOM.jl) until I had updated my TagBot file to match what the developers recommended.

See the [TagBot issue](https://github.com/SamuraiAku/PkgToSoftwareBOM.jl/issues/12) in my repository.

**Comment by oxinabox** [comment]
A PR updating it would be appreciated
