### ISSUE TITLE
Can't create Plugin

### ISSUE THREAD

**Issue by cossio** [JuliaCI/PkgTemplates.jl#418]
```
julia> using PkgTemplates: @with_kw_noshow, @plugin, FilePlugin
julia> @plugin struct Changelog <: FilePlugin
           file::String = "CHANGELOG.md"
       end
ERROR: UndefVarError: `PkgTemplates` not defined
Stacktrace:
 [1] top-level scope
   @ ~/.julia/packages/PkgTemplates/LISo2/src/plugin.jl:67
```

Am I doing something wrong?

```
Julia Version 1.9.2
[14b8a8f1] PkgTemplates v0.7.38
```

**Comment by oxinabox** [comment]
you need to have:
`using PkgTemplates: PkgTemplates, @with_kw_noshow, @plugin, FilePlugin`

because the `@plugin` macro assumed that the PkgTemplates is defined where it is called.
We could fix this by interpolating all the functions generated in the macro, but it would take a bit.
