### ISSUE TITLE
Suggestion: Create files for use with PkgBenchmark.jl

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaCI/PkgTemplates.jl#86]
It would be great if PkgTemplates.jl could generate the files for using [PkgBenchmark.jl](https://github.com/JuliaCI/PkgBenchmark.jl) on your Julia package.

Probably the most important file would be the `<PKGROOT>/benchmark/benchmarks.jl` file as described [here](https://juliaci.github.io/PkgBenchmark.jl/stable/define_benchmarks.html) and [here](https://github.com/JuliaCI/BenchmarkTools.jl/blob/master/doc/manual.md#defining-benchmark-suites). An example `benchmark/benchmarks.jl` file is available [here](https://github.com/JuliaCI/PkgBenchmark.jl/blob/master/benchmark/benchmarks.jl).

**Comment by nickrobinson251** [comment]
Perhaps optionally? I don't _think_ it would be useful for most cases (most packages don't have benchmarks), but it would be nice to have the option (I know I've wondered how best to add benchmarks to a package)?

**Comment by DilumAluthge** [comment]
> Perhaps optionally? I don't think it would be useful for most cases (most packages don't have benchmarks), but it would be nice to have the option (I know I've wondered how best to add benchmarks to a package)?

I agree. Definitely it should be optional.

**Comment by gdalle** [comment]
Done in #261
